version: '3.1'
services:
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always

  web:
    build: .
    depends_on:
      - db
    links:
      - db
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - RAILS_SERVE_STATIC_FILES=true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -b unix:///oyak_omu_edu_tr/tmp/sockets/oyak_puma_unix.sock"
    volumes:
      - .:/oyak_omu_edu_tr
    restart: always