default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 3306
  socket: /tmp/mysql.sock
  username: <%= ENV.fetch("MYSQL_USER_NAME") %>
  password: <%= ENV.fetch("MYSQL_USER_PASSWORD") %>

development:
  <<: *default
  database: oyak_omu_edu_tr_development

test:
  <<: *default
  database: oyak_omu_edu_tr_test

production:
  <<: *default
  database: oyak_omu_edu_tr_production
